# Generated by Django 5.1.2 on 2024-10-26 07:32

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=Users.models.generate_user_id, max_length=6, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=50)),
                ('occupation', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('withdraw_method', models.CharField(choices=[('BANK', 'Bank'), ('UPI', 'UPI')], default='UPI', max_length=50)),
                ('withdraw_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ufsc', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
    ]
